environment:
  global:
    GITHUB_USER_PASSWORD:
      secure: iJyVR7z6BkcqxkctwnDldPxLBNLKfO1qD3EchXiH0fimfDx1oq2gGQyfG4/NtfGX

  matrix:
    # LEVEL=1 {
    - TOOLCHAIN: "vs-14-2015-sdk-8-1"
      LEVEL: 1
    - TOOLCHAIN: "vs-14-2015-win64-sdk-8-1"
      LEVEL: 1
    # }

    # LEVEL=2 {
    - TOOLCHAIN: "vs-14-2015-sdk-8-1"
      LEVEL: 2
    - TOOLCHAIN: "vs-14-2015-win64-sdk-8-1"
      LEVEL: 2
    # }

    # LEVEL=3 {
    - TOOLCHAIN: "vs-14-2015-sdk-8-1"
      LEVEL: 3
    - TOOLCHAIN: "vs-14-2015-win64-sdk-8-1"
      LEVEL: 3
    # }

install:
  # Python 3
  - cmd: set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%

  # Install Python package 'requests'
  - cmd: pip install requests

  # Install latest Polly toolchains and scripts
  - cmd: appveyor DownloadFile https://github.com/ruslo/polly/archive/master.zip
  - cmd: 7z x master.zip
  - cmd: set POLLY_ROOT=%cd%\polly-master

  # Install dependencies (CMake, Ninja)
  - cmd: python %POLLY_ROOT%\bin\install-ci-dependencies.py

  # Tune locations
  - cmd: set PATH=%cd%\_ci\cmake\bin;%PATH%
  - cmd: set PATH=%cd%\_ci\ninja;%PATH%

  - git submodule update --init --recursive

  # Remove entry with sh.exe from PATH to fix error with MinGW toolchain
  # (For MinGW make to work correctly sh.exe must NOT be in your path)
  # * http://stackoverflow.com/a/3870338/2288008
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

  # Use MinGW from Qt tools because version is higher
  # * http://www.appveyor.com/docs/installed-software#qt
  - cmd: set MINGW_PATH=C:\Qt\Tools\mingw492_32\bin

  # MSYS2 location
  - cmd: set MSYS_PATH=C:\msys64\usr\bin

build_script:
  # Build dependencies
  - cmd: python %POLLY_ROOT%\bin\polly.py --toolchain "%TOOLCHAIN%" --verbose

  # Upload to server
  - cmd: git clone https://github.com/ruslo/hunter
  - cmd: python %cd%\hunter\maintenance\upload-cache-to-github.py --username jalandhara --repo-owner elucideye --repo hunter-cache --cache-dir C:/Users/appveyor/.hunter/_Base/Cache --temp-dir C:/Users/appveyor/__TEMP_HUNTER

branches:
  except:
    - /^pr\..*/
